-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Drop tables if they exist (for easy resetting)
DROP TABLE IF EXISTS proposals CASCADE;
DROP TABLE IF EXISTS client_needs CASCADE;
DROP TABLE IF EXISTS smls CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- Create Users Table
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('client', 'admin')),
    company_name VARCHAR(255),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create SMLs Table
CREATE TABLE smls (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    category VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    base_model_type VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Client Needs Table
CREATE TABLE client_needs (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_id UUID REFERENCES users(id) ON DELETE CASCADE,
    problem_description TEXT NOT NULL,
    expected_users_concurrent INTEGER NOT NULL,
    data_sensitivity VARCHAR(50) NOT NULL CHECK (data_sensitivity IN ('low', 'medium', 'high', 'critical')),
    use_cases_priority JSONB NOT NULL,
    current_ia_pain_points TEXT,
    status VARCHAR(50) NOT NULL DEFAULT 'submitted' CHECK (status IN ('draft', 'submitted', 'reviewed', 'proposal_generated')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Proposals Table
CREATE TABLE proposals (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    client_need_id UUID REFERENCES client_needs(id) ON DELETE CASCADE UNIQUE,
    recommended_sml_ids JSONB NOT NULL, -- Array of UUIDs
    recommended_nodo_type VARCHAR(50) NOT NULL CHECK (recommended_nodo_type IN ('Starter', 'Enterprise', 'Sovereign', 'Custom')),
    estimated_fixed_cost_usd NUMERIC(10, 2) NOT NULL,
    estimated_amortization_months INTEGER NOT NULL,
    proposal_details TEXT NOT NULL,
    hardware_specs JSON DEFAULT '{}',
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Initial Users (Password: password123)
-- bcrypt hash for 'password123'
INSERT INTO users (id, email, password_hash, role, company_name) VALUES
('a3b7c9e1-2d4e-4f6a-8b0c-1d2e3f4a5b6c', 'admin@proxdeep.com', '$2a$10$j3Q8XLEZXZ85cxFKw5.wG.PFI6ynXliTE9/aOqXTLXVLPFb7uYU5u', 'admin', 'ProxDeep Corp'),
('b5c8d0e2-3f5a-5b7c-9d1e-2f3a4b5c6d7e', 'client@acme.com', '$2a$10$j3Q8XLEZXZ85cxFKw5.wG.PFI6ynXliTE9/aOqXTLXVLPFb7uYU5u', 'client', 'Acme Corporation');

-- Seed SMLs Catalogue
INSERT INTO smls (id, name, category, description, base_model_type, is_active) VALUES
('11111111-1111-1111-1111-111111111111', 'Clasificador de Documentos Financieros', 'Análisis Documental', 'SML optimizado para clasificar facturas, balances y reportes fiscales con 99% de precisión local. Minimiza el riesgo de exposición de datos sensibles y acelera auditorías internas.', 'Mistral-7B', TRUE),
('22222222-2222-2222-2222-222222222222', 'Asistente de Soporte Médico', 'Atención al Cliente', 'Ajustado finamente con guías clínicas internacionales y regulaciones locales para triaje y asistencia de pacientes en entornos hospitalarios seguros, garantizando la privacidad de historias clínicas.', 'Llama-3-8B', TRUE),
('33333333-3333-3333-3333-333333333333', 'Redactor de Contratos Legales', 'Generación de Contenido', 'Modelo ligero especializado en la redacción y revisión automatizada de contratos de confidencialidad (NDA), acuerdos comerciales y términos de servicio bajo regulaciones locales.', 'Phi-3-Medium', TRUE),
('44444444-4444-4444-4444-444444444444', 'Extractor de Entidades Regulatorias', 'Análisis Documental', 'Extrae automáticamente nombres, fechas, montos y cláusulas regulatorias en archivos escaneados pesados para agilizar la conformidad regulatoria empresarial.', 'Llama-3-8B', TRUE),
('55555555-5555-5555-5555-555555555555', 'Analista de Feedback de Clientes', 'Atención al Cliente', 'SML optimizado para analizar opiniones, encuestas de satisfacción y transcripciones de llamadas para detectar sentimientos y temas clave sin externalizar datos de clientes.', 'Mistral-7B', TRUE);

-- Modelos Adicionales de ProxDeep Ecosystem
INSERT INTO smls (name, category, description, base_model_type, is_active) VALUES
('DeepSeek-Coder-V2', 'Código y Desarrollo', 'Modelo de última generación especializado en generación, refactorización y depuración de código en múltiples lenguajes.', 'DeepSeek-V2', TRUE),
('Qwen2.5-Coder', 'Código y Desarrollo', 'Extraordinario rendimiento en tareas de programación, superando a modelos mucho más grandes. Ideal para auto-completado corporativo.', 'Qwen2.5-7B', TRUE),
('Phind-CodeLlama', 'Código y Desarrollo', 'Optimizado para responder preguntas de programación y ayudar a equipos de desarrollo a escalar internamente.', 'CodeLlama-34B', TRUE),
('LLaVA-1.5', 'Visión y Multimodal', 'Analiza imágenes complejas, diagramas y fotografías con gran precisión para tareas de mantenimiento e inspección.', 'LLaVA-13B', TRUE),
('Qwen-VL-Max', 'Visión y Multimodal', 'Lectura de OCR avanzado, análisis de documentos escaneados y extracción visual de datos no estructurados.', 'Qwen-VL', TRUE),
('MedLlama-3', 'Salud y BioMedicina', 'SML especializado con corpus médico extenso. Ayuda a pre-diagnósticos, análisis de síntomas y gestión clínica.', 'Llama-3-8B', TRUE),
('BioMistral', 'Salud y BioMedicina', 'Destaca en la comprensión de literatura médica y en la estructuración de historiales clínicos desordenados.', 'Mistral-7B', TRUE),
('FinGPT', 'Finanzas y Auditoría', 'Ajustado para el mercado financiero, análisis de sentimiento de noticias económicas e investigación cuantitativa.', 'Llama-3-8B', TRUE),
('Bloomberg-Lite', 'Finanzas y Auditoría', 'Asistente enfocado en procesar terminales financieras, balances anuales y ratios contables complejos.', 'Mistral-7B', TRUE),
('SaulLM-7B', 'Legal y Cumplimiento', 'El primer LLM entrenado exclusivamente sobre corpus legales masivos. Excelente para entender la jerga de abogados.', 'Mistral-7B', TRUE),
('Mistral-Nemo-Legal', 'Legal y Cumplimiento', 'Adaptación del modelo Nemo con foco en cumplimiento normativo (Compliance) corporativo.', 'Mistral-Nemo-12B', TRUE),
('Llama-3-70B-Instruct', 'Agentes y RAG', 'Modelo "Heavy" para tareas complejas de orquestación de agentes, razonamiento de múltiples pasos y sistemas RAG.', 'Llama-3-70B', TRUE),
('Mixtral-8x7B', 'Agentes y RAG', 'Arquitectura Mixture of Experts (MoE). Combina velocidad y rendimiento de grado GPT-3.5 para enrutamiento inteligente.', 'Mixtral-MoE', TRUE),
('Gemma-2-9B-It', 'Generación de Contenido', 'Poderoso modelo de Google Open Source para tareas de redacción corporativa, emails y generación de minutas.', 'Gemma-2', TRUE),
('Qwen2-Math', 'Análisis de Datos', 'Especialista en razonamiento matemático, estadística y cálculos corporativos complejos sin alucinaciones.', 'Qwen2', TRUE);

-- Seed Client Needs (Acme Corp has already submitted a diagnostic)
INSERT INTO client_needs (id, client_id, problem_description, expected_users_concurrent, data_sensitivity, use_cases_priority, current_ia_pain_points, status) VALUES
('99999999-9999-9999-9999-999999999999', 'b5c8d0e2-3f5a-5b7c-9d1e-2f3a4b5c6d7e', 'Necesitamos analizar miles de contratos comerciales confidenciales diariamente y extraer cláusulas de renovación automáticas. No podemos usar APIs de nube públicas debido a políticas estrictas de privacidad corporativa.', 50, 'high', '["resumen_legal", "extraccion_entidades"]', 'Fuga de datos a servidores extranjeros y costos de API impredecibles.', 'proposal_generated');

-- Seed Proposal for Acme Corp (Linked to their client need)
INSERT INTO proposals (id, client_need_id, recommended_sml_ids, recommended_nodo_type, estimated_fixed_cost_usd, estimated_amortization_months, proposal_details, status) VALUES
('88888888-8888-8888-8888-888888888888', '99999999-9999-9999-9999-999999999999', '["33333333-3333-3333-3333-333333333333", "44444444-4444-4444-4444-444444444444"]', 'Sovereign', 12500.00, 6, 'Se propone desplegar un Nodo ProxDeep en la nube privada de Acme Corp (on-premises o VPS dedicado). El nodo correrá dos SMLs optimizados: "Redactor de Contratos Legales" para revisión y "Extractor de Entidades Regulatorias" para la extracción de cláusulas. Costo fijo de instalación y licencias de software por única vez. Sin costos variables por volumen.', 'pending');

-- Auto-generado 500 modelos adicionales
INSERT INTO smls (name, category, description, base_model_type, is_active) VALUES
('Mistral-FinAI-34B', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Mistral-34B', TRUE),
('Microsoft-Agent-34B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Microsoft-34B', TRUE),
('EyeLM-34B-v1.2', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Qwen-34B', TRUE),
('Nexus-ContractAI-4x8B', 'Legal y Cumplimiento', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nexus-4x8B', TRUE),
('HuggingFace-Data-8B', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'HuggingFace-8B', TRUE),
('IBM-Law-MoE-Sparse', 'Legal y Cumplimiento', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'IBM-MoE-Sparse', TRUE),
('ProxDeep-Coder-MoE-Sparse-Instruct', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Qwen-MoE-Sparse', TRUE),
('DeepSeek-SyntaxAI-8x7B', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'DeepSeek-8x7B', TRUE),
('ProxDeep-Data-7B-Instruct', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'ProxDeep-7B', TRUE),
('Fin-TII-v4.0', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'TII-7B', TRUE),
('Qwen-Eye-8x7B', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Qwen-8x7B', TRUE),
('ProxDeep-Lex-72B-Instruct', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', '01.AI-72B', TRUE),
('LegalLM-34B-v2.0', 'Legal y Cumplimiento', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'HuggingFace-34B', TRUE),
('Upstage-EconAI-110B', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Upstage-110B', TRUE),
('DeepSeek-DoctorAI-34B', 'Salud y BioMedicina', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'DeepSeek-34B', TRUE),
('TII-AnalyticsAI-13B', 'Análisis de Datos', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'TII-13B', TRUE),
('ImageLM-72B-v1.0', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'IBM-72B', TRUE),
('Content-DeepSeek-v1.5', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'DeepSeek-8B', TRUE),
('RAG-Google-v4.5', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Google-70B', TRUE),
('CodeLlamaLM-13B-v1.2', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'IBM-13B', TRUE),
('ProxDeep-Coder-70B-Instruct', 'Código y Desarrollo', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Google-70B', TRUE),
('JusticeLM-70B-v1.1', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Salesforce-70B', TRUE),
('ProxDeep-Doctor-34B-Instruct', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Upstage-34B', TRUE),
('Meta-HealthAI-72B', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Meta-72B', TRUE),
('IBM-VL-8B', 'Visión y Multimodal', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'IBM-8B', TRUE),
('Stability-AuditAI-13B', 'Finanzas y Auditoría', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-13B', TRUE),
('Anthropic-EconAI-34B', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-34B', TRUE),
('Microsoft-Analytics-70B', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Microsoft-70B', TRUE),
('SyntaxLM-4x8B-v4.5', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nvidia-4x8B', TRUE),
('CareLM-4x8B-v4.1', 'Salud y BioMedicina', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Salesforce-4x8B', TRUE),
('EleutherAI-LedgerAI-72B', 'Finanzas y Auditoría', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'EleutherAI-72B', TRUE),
('TII-RAG-13B', 'Agentes y RAG', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-13B', TRUE),
('DataLM-13B-v3.1', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-13B', TRUE),
('Anthropic-LogicAI-32B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-32B', TRUE),
('ProxDeep-Doctor-13B-Instruct', 'Salud y BioMedicina', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Mistral-13B', TRUE),
('AgentLM-32B-v2.2', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'TII-32B', TRUE),
('HuggingFace-BioAI-7B', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-7B', TRUE),
('MarketLM-MoE-Sparse-v2.5', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'DeepSeek-MoE-Sparse', TRUE),
('Nvidia-AgentAI-8B', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-8B', TRUE),
('Qwen-SightAI-MoE-Sparse', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Qwen-MoE-Sparse', TRUE),
('Audit-Microsoft-v3.4', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Microsoft-34B', TRUE),
('MarketLM-4x8B-v4.5', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'IBM-4x8B', TRUE),
('OrchestratorLM-70B-v4.0', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Microsoft-70B', TRUE),
('HuggingFace-Law-14B', 'Legal y Cumplimiento', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'HuggingFace-14B', TRUE),
('01.AI-Copy-MoE-Sparse', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', '01.AI-MoE-Sparse', TRUE),
('Nvidia-CalcAI-72B', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Nvidia-72B', TRUE),
('ChatLM-MoE-Sparse-v4.1', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Mistral-MoE-Sparse', TRUE),
('Cohere-Multi-8B', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Cohere-8B', TRUE),
('Orchestrator-Nvidia-v4.5', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nvidia-8B', TRUE),
('Calc-Stability-v4.2', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Stability-4x8B', TRUE),
('Creative-Salesforce-v4.3', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Salesforce-8B', TRUE),
('MultiLM-8B-v3.1', 'Visión y Multimodal', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'EleutherAI-8B', TRUE),
('Legal-DeepSeek-v2.5', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'DeepSeek-4x8B', TRUE),
('ProxDeep-Justice-14B-Instruct', 'Legal y Cumplimiento', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Qwen-14B', TRUE),
('Upstage-RAGAI-8B', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Upstage-8B', TRUE),
('AuditLM-32B-v4.3', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'HuggingFace-32B', TRUE),
('LawLM-32B-v3.1', 'Legal y Cumplimiento', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Microsoft-32B', TRUE),
('IBM-CopyAI-32B', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'IBM-32B', TRUE),
('Eye-Meta-v1.3', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Meta-72B', TRUE),
('ProxDeep-Pharma-8x7B-Instruct', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Upstage-8x7B', TRUE),
('ProxDeep-Build-13B-Instruct', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Nvidia-13B', TRUE),
('HuggingFace-ProgrammerAI-4x8B', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'HuggingFace-4x8B', TRUE),
('EleutherAI-Text-32B', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'EleutherAI-32B', TRUE),
('TII-RAG-4x8B', 'Agentes y RAG', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-4x8B', TRUE),
('Anthropic-MathAI-34B', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-34B', TRUE),
('EyeLM-32B-v4.5', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-32B', TRUE),
('Stability-Orchestrator-110B', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Stability-110B', TRUE),
('Salesforce-Instruct-8B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Salesforce-8B', TRUE),
('LexLM-4x8B-v1.2', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', '01.AI-4x8B', TRUE),
('Cohere-ChatAI-13B', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Cohere-13B', TRUE),
('Audit-Google-v3.5', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Google-MoE-Sparse', TRUE),
('ProxDeep-Copy-72B-Instruct', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Cohere-72B', TRUE),
('ProxDeep-Trade-13B-Instruct', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Meta-13B', TRUE),
('Upstage-MultiAI-MoE-Sparse', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Upstage-MoE-Sparse', TRUE),
('Content-IBM-v1.0', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'IBM-MoE-Sparse', TRUE),
('Upstage-AuditAI-34B', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Upstage-34B', TRUE),
('EngineLM-7B-v4.1', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Microsoft-7B', TRUE),
('Cohere-CodeLlama-110B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Cohere-110B', TRUE),
('Orchestrator-ProxDeep-v2.1', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'ProxDeep-14B', TRUE),
('LexLM-110B-v4.0', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Anthropic-110B', TRUE),
('ProxDeep-Lex-4x8B-Instruct', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Mistral-4x8B', TRUE),
('Salesforce-FinAI-4x8B', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Salesforce-4x8B', TRUE),
('ProxDeep-Contract-110B-Instruct', 'Legal y Cumplimiento', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-110B', TRUE),
('HuggingFace-StatsAI-8x7B', 'Análisis de Datos', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'HuggingFace-8x7B', TRUE),
('Content-Salesforce-v2.0', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Salesforce-110B', TRUE),
('ProxDeep-Econ-72B-Instruct', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Meta-72B', TRUE),
('ChatLM-MoE-Sparse-v3.3', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'HuggingFace-MoE-Sparse', TRUE),
('ProxDeep-Med-7B-Instruct', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'DeepSeek-7B', TRUE),
('ProxDeep-Logic-34B-Instruct', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Anthropic-34B', TRUE),
('ProxDeep-Trade-14B-Instruct', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Upstage-14B', TRUE),
('ProxDeep-Trade-110B-Instruct', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Cohere-110B', TRUE),
('01.AI-Text-4x8B', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', '01.AI-4x8B', TRUE),
('Dev-IBM-v3.0', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'IBM-7B', TRUE),
('HuggingFace-DraftAI-8B', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'HuggingFace-8B', TRUE),
('Stability-ComplianceAI-MoE-Sparse', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Stability-MoE-Sparse', TRUE),
('ProxDeep-RAG-32B', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'ProxDeep-32B', TRUE),
('Nexus-ContractAI-8B', 'Legal y Cumplimiento', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nexus-8B', TRUE),
('Nvidia-RAGAI-14B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Nvidia-14B', TRUE),
('01.AI-Law-70B', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', '01.AI-70B', TRUE),
('Google-Clinical-8B', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Google-8B', TRUE),
('ProxDeep-Quant-13B', 'Finanzas y Auditoría', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'ProxDeep-13B', TRUE),
('TextLM-70B-v4.2', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Google-70B', TRUE),
('ProxDeep-Build-4x8B-Instruct', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', '01.AI-4x8B', TRUE),
('JusticeLM-13B-v2.3', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Meta-13B', TRUE),
('ProxDeep-Doctor-72B-Instruct', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Microsoft-72B', TRUE),
('VisionLM-34B-v3.4', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Stability-34B', TRUE),
('Meta-Scan-72B', 'Visión y Multimodal', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Meta-72B', TRUE),
('Multi-Nvidia-v1.3', 'Visión y Multimodal', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nvidia-7B', TRUE),
('Law-Google-v1.1', 'Legal y Cumplimiento', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Google-MoE-Sparse', TRUE),
('SightLM-13B-v3.4', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'TII-13B', TRUE),
('Logic-ProxDeep-v1.0', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'ProxDeep-8x7B', TRUE),
('Cohere-Care-8B', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Cohere-8B', TRUE),
('Nexus-Vision-34B', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Nexus-34B', TRUE),
('Salesforce-Data-MoE-Sparse', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Salesforce-MoE-Sparse', TRUE),
('ProxDeep-Writer-MoE-Sparse-Instruct', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Upstage-MoE-Sparse', TRUE),
('VL-DeepSeek-v3.0', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'DeepSeek-8B', TRUE),
('Mistral-DevAI-110B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Mistral-110B', TRUE),
('Cohere-LedgerAI-MoE-Sparse', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Cohere-MoE-Sparse', TRUE),
('Calc-Anthropic-v1.4', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-34B', TRUE),
('Ledger-Stability-v4.0', 'Finanzas y Auditoría', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Stability-4x8B', TRUE),
('ProxDeep-Doctor-MoE-Sparse-Instruct', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Nvidia-MoE-Sparse', TRUE),
('ProxDeep-Scan-14B-Instruct', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'IBM-14B', TRUE),
('Stability-VisionAI-34B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-34B', TRUE),
('Meta-LawAI-70B', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Meta-70B', TRUE),
('InstructLM-13B-v4.5', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nvidia-13B', TRUE),
('WriterLM-13B-v3.4', 'Generación de Contenido', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'IBM-13B', TRUE),
('ProxDeep-Compliance-8B-Instruct', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Anthropic-8B', TRUE),
('Meta-Law-32B', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Meta-32B', TRUE),
('TII-DraftAI-110B', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'TII-110B', TRUE),
('ProxDeep-Eye-70B-Instruct', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Salesforce-70B', TRUE),
('Multi-Anthropic-v2.1', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-34B', TRUE),
('Salesforce-CreativeAI-70B', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Salesforce-70B', TRUE),
('Google-Text-34B', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Google-34B', TRUE),
('Reasoning-TII-v3.2', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'TII-34B', TRUE),
('Microsoft-Doctor-13B', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Microsoft-13B', TRUE),
('Nexus-Doctor-110B', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nexus-110B', TRUE),
('Doctor-Nvidia-v1.1', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Nvidia-34B', TRUE),
('TII-VLAI-32B', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'TII-32B', TRUE),
('Qwen-Creative-32B', 'Generación de Contenido', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Qwen-32B', TRUE),
('EngineLM-34B-v3.2', 'Análisis de Datos', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Google-34B', TRUE),
('Text-Mistral-v2.3', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Mistral-72B', TRUE),
('VLLM-32B-v1.1', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Cohere-32B', TRUE),
('Nexus-MoEAI-13B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Nexus-13B', TRUE),
('ProxDeep-Market-14B-Instruct', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Upstage-14B', TRUE),
('MultiLM-34B-v1.0', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'TII-34B', TRUE),
('TII-ComplianceAI-4x8B', 'Legal y Cumplimiento', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'TII-4x8B', TRUE),
('ProxDeep-VL-4x8B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'ProxDeep-4x8B', TRUE),
('ProxDeep-Sight-32B-Instruct', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'ProxDeep-32B', TRUE),
('Nvidia-Image-70B', 'Visión y Multimodal', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nvidia-70B', TRUE),
('Qwen-InstructAI-13B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Qwen-13B', TRUE),
('01.AI-ClinicalAI-8B', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', '01.AI-8B', TRUE),
('ProxDeep-Sight-8x7B-Instruct', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'IBM-8x7B', TRUE),
('ProxDeep-Content-MoE-Sparse-Instruct', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-MoE-Sparse', TRUE),
('Stability-Pharma-110B', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Stability-110B', TRUE),
('Mistral-Multi-MoE-Sparse', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Mistral-MoE-Sparse', TRUE),
('MedLM-14B-v4.4', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nexus-14B', TRUE),
('DeepSeek-Copy-32B', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'DeepSeek-32B', TRUE),
('BuildLM-8x7B-v4.1', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Stability-8x7B', TRUE),
('ProxDeep-Programmer-13B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'ProxDeep-13B', TRUE),
('ProxDeep-Build-32B-Instruct', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Nvidia-32B', TRUE),
('Google-Analytics-7B', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Google-7B', TRUE),
('ProxDeep-Text-MoE-Sparse-Instruct', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Stability-MoE-Sparse', TRUE),
('Stats-TII-v2.2', 'Análisis de Datos', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-8B', TRUE),
('ProxDeep-VL-MoE-Sparse-Instruct', 'Visión y Multimodal', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Meta-MoE-Sparse', TRUE),
('Med-Nvidia-v4.1', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nvidia-8x7B', TRUE),
('Salesforce-ImageAI-110B', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Salesforce-110B', TRUE),
('ClinicalLM-MoE-Sparse-v3.0', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Mistral-MoE-Sparse', TRUE),
('Writer-Nvidia-v3.3', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nvidia-7B', TRUE),
('Nexus-Creative-4x8B', 'Generación de Contenido', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nexus-4x8B', TRUE),
('HuggingFace-SightAI-110B', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'HuggingFace-110B', TRUE),
('ProxDeep-Content-70B-Instruct', 'Generación de Contenido', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Microsoft-70B', TRUE),
('EleutherAI-Ledger-7B', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'EleutherAI-7B', TRUE),
('Coder-Qwen-v4.4', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Qwen-32B', TRUE),
('Analytics-Salesforce-v1.2', 'Análisis de Datos', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Salesforce-4x8B', TRUE),
('Compliance-Salesforce-v1.0', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Salesforce-34B', TRUE),
('Mistral-Coder-72B', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Mistral-72B', TRUE),
('ProxDeep-Health-110B-Instruct', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Nexus-110B', TRUE),
('01.AI-Quant-14B', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', '01.AI-14B', TRUE),
('ProxDeep-Data-4x8B-Instruct', 'Análisis de Datos', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-4x8B', TRUE),
('ProxDeep-Clinical-4x8B-Instruct', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Microsoft-4x8B', TRUE),
('LexLM-8x7B-v1.3', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'DeepSeek-8x7B', TRUE),
('Qwen-CopyAI-32B', 'Generación de Contenido', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Qwen-32B', TRUE),
('01.AI-DoctorAI-110B', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', '01.AI-110B', TRUE),
('Legal-Qwen-v2.0', 'Legal y Cumplimiento', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Qwen-8B', TRUE),
('TextLM-70B-v2.0', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Qwen-70B', TRUE),
('Stats-Nexus-v3.1', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nexus-110B', TRUE),
('Data-Cohere-v1.1', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Cohere-70B', TRUE),
('VLLM-72B-v3.4', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'TII-72B', TRUE),
('VL-01.AI-v2.0', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', '01.AI-14B', TRUE),
('Clinical-Nvidia-v2.3', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nvidia-14B', TRUE),
('Nvidia-MoE-32B', 'Agentes y RAG', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nvidia-32B', TRUE),
('Google-LawAI-13B', 'Legal y Cumplimiento', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Google-13B', TRUE),
('AgentLM-14B-v1.4', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-14B', TRUE),
('MarketLM-7B-v3.0', 'Finanzas y Auditoría', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', '01.AI-7B', TRUE),
('ProxDeep-JusticeAI-32B', 'Legal y Cumplimiento', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'ProxDeep-32B', TRUE),
('HealthLM-4x8B-v2.2', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Mistral-4x8B', TRUE),
('ProxDeep-Compliance-8x7B-Instruct', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', '01.AI-8x7B', TRUE),
('DeepSeek-Clinical-110B', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'DeepSeek-110B', TRUE),
('Vision-Anthropic-v3.4', 'Visión y Multimodal', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Anthropic-72B', TRUE),
('ComplianceLM-70B-v2.2', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-70B', TRUE),
('TII-Stats-MoE-Sparse', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'TII-MoE-Sparse', TRUE),
('Cohere-Trade-13B', 'Finanzas y Auditoría', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Cohere-13B', TRUE),
('ProxDeep-Orchestrator-14B-Instruct', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-14B', TRUE),
('ProxDeep-Compliance-70B-Instruct', 'Legal y Cumplimiento', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nexus-70B', TRUE),
('Compliance-Qwen-v4.0', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Qwen-34B', TRUE),
('Upstage-Writer-13B', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Upstage-13B', TRUE),
('Qwen-Draft-8x7B', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Qwen-8x7B', TRUE),
('ProxDeep-Text-34B-Instruct', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'DeepSeek-34B', TRUE),
('Upstage-Doctor-8x7B', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Upstage-8x7B', TRUE),
('HuggingFace-SightAI-32B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'HuggingFace-32B', TRUE),
('TII-Reasoning-13B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'TII-13B', TRUE),
('ProxDeep-Sight-72B-Instruct', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Nexus-72B', TRUE),
('Anthropic-Programmer-MoE-Sparse', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Anthropic-MoE-Sparse', TRUE),
('ProxDeep-Sight-14B-Instruct', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Cohere-14B', TRUE),
('CodeLlamaLM-13B-v1.1', 'Código y Desarrollo', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Mistral-13B', TRUE),
('Stability-CodeLlamaAI-110B', 'Código y Desarrollo', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Stability-110B', TRUE),
('ProxDeep-Dev-32B-Instruct', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Upstage-32B', TRUE),
('ProxDeep-PharmaAI-110B', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'ProxDeep-110B', TRUE),
('Legal-Nvidia-v2.1', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Nvidia-32B', TRUE),
('Qwen-BuildAI-7B', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Qwen-7B', TRUE),
('ContractLM-70B-v1.4', 'Legal y Cumplimiento', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Qwen-70B', TRUE),
('EleutherAI-Chat-13B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'EleutherAI-13B', TRUE),
('AnalyticsLM-MoE-Sparse-v4.2', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'EleutherAI-MoE-Sparse', TRUE),
('ProxDeep-CareAI-110B', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'ProxDeep-110B', TRUE),
('IBM-LogicAI-110B', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'IBM-110B', TRUE),
('IBM-LedgerAI-8B', 'Finanzas y Auditoría', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'IBM-8B', TRUE),
('Nexus-Stats-4x8B', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nexus-4x8B', TRUE),
('Anthropic-Doctor-72B', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Anthropic-72B', TRUE),
('ProxDeep-Sight-4x8B-Instruct', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Stability-4x8B', TRUE),
('Analytics-Qwen-v4.2', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Qwen-34B', TRUE),
('HuggingFace-CreativeAI-70B', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-70B', TRUE),
('ComplianceLM-7B-v2.2', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'DeepSeek-7B', TRUE),
('ProxDeep-Market-8B-Instruct', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Meta-8B', TRUE),
('InstructLM-8x7B-v2.5', 'Agentes y RAG', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'HuggingFace-8x7B', TRUE),
('Qwen-Market-8B', 'Finanzas y Auditoría', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Qwen-8B', TRUE),
('Qwen-RAG-MoE-Sparse', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Qwen-MoE-Sparse', TRUE),
('ProxDeep-Chat-7B-Instruct', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Mistral-7B', TRUE),
('LogicLM-34B-v4.5', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'IBM-34B', TRUE),
('EleutherAI-BuildAI-32B', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'EleutherAI-32B', TRUE),
('ProxDeep-Logic-110B-Instruct', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'ProxDeep-110B', TRUE),
('EleutherAI-Stats-13B', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'EleutherAI-13B', TRUE),
('TII-VLAI-13B', 'Visión y Multimodal', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'TII-13B', TRUE),
('Clinical-Upstage-v1.4', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Upstage-13B', TRUE),
('CodeLlama-IBM-v1.4', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'IBM-8B', TRUE),
('01.AI-Agent-110B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', '01.AI-110B', TRUE),
('Anthropic-FinAI-8x7B', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Anthropic-8x7B', TRUE),
('Nexus-Ledger-13B', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Nexus-13B', TRUE),
('Anthropic-VisionAI-4x8B', 'Visión y Multimodal', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Anthropic-4x8B', TRUE),
('ProxDeep-Coder-14B-Instruct', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-14B', TRUE),
('Meta-Programmer-14B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Meta-14B', TRUE),
('Anthropic-EyeAI-4x8B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-4x8B', TRUE),
('Qwen-MedAI-4x8B', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Qwen-4x8B', TRUE),
('EleutherAI-Engine-13B', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'EleutherAI-13B', TRUE),
('Writer-Salesforce-v1.0', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Salesforce-7B', TRUE),
('ComplianceLM-8x7B-v1.0', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'TII-8x7B', TRUE),
('ProxDeep-Coder-8B-Instruct', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Mistral-8B', TRUE),
('ProxDeep-Legal-8x7B-Instruct', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'HuggingFace-8x7B', TRUE),
('ProxDeep-Bio-MoE-Sparse-Instruct', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Upstage-MoE-Sparse', TRUE),
('TII-MedAI-34B', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'TII-34B', TRUE),
('Scan-TII-v4.0', 'Visión y Multimodal', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'TII-MoE-Sparse', TRUE),
('Upstage-Content-72B', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Upstage-72B', TRUE),
('Nvidia-Fin-8B', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Nvidia-8B', TRUE),
('DeepSeek-Programmer-4x8B', 'Código y Desarrollo', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'DeepSeek-4x8B', TRUE),
('Build-Microsoft-v2.5', 'Código y Desarrollo', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Microsoft-8x7B', TRUE),
('Image-Upstage-v3.0', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Upstage-32B', TRUE),
('Microsoft-VisionAI-32B', 'Visión y Multimodal', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Microsoft-32B', TRUE),
('Microsoft-ContentAI-13B', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Microsoft-13B', TRUE),
('ProxDeep-Med-MoE-Sparse-Instruct', 'Salud y BioMedicina', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Qwen-MoE-Sparse', TRUE),
('Meta-Lex-8B', 'Legal y Cumplimiento', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Meta-8B', TRUE),
('Stability-Ledger-34B', 'Finanzas y Auditoría', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Stability-34B', TRUE),
('Draft-Qwen-v4.3', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Qwen-13B', TRUE),
('ProxDeep-Writer-7B-Instruct', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Cohere-7B', TRUE),
('ProxDeep-Stats-34B-Instruct', 'Análisis de Datos', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Stability-34B', TRUE),
('ProxDeep-Sight-13B-Instruct', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'HuggingFace-13B', TRUE),
('DevLM-110B-v1.0', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Mistral-110B', TRUE),
('ProxDeep-Quant-7B-Instruct', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-7B', TRUE),
('EleutherAI-WriterAI-72B', 'Generación de Contenido', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'EleutherAI-72B', TRUE),
('LogicLM-8B-v4.1', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Stability-8B', TRUE),
('HuggingFace-AuditAI-13B', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'HuggingFace-13B', TRUE),
('IBM-AgentAI-13B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'IBM-13B', TRUE),
('ProxDeep-Law-110B', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'ProxDeep-110B', TRUE),
('Mistral-Math-8x7B', 'Análisis de Datos', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Mistral-8x7B', TRUE),
('Google-TextAI-34B', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Google-34B', TRUE),
('Mistral-Bio-110B', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Mistral-110B', TRUE),
('Copy-Cohere-v1.3', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Cohere-MoE-Sparse', TRUE),
('Qwen-Chat-8B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Qwen-8B', TRUE),
('ProxDeep-Reasoning-13B-Instruct', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Microsoft-13B', TRUE),
('WriterLM-70B-v2.4', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nvidia-70B', TRUE),
('MoE-01.AI-v1.3', 'Agentes y RAG', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', '01.AI-110B', TRUE),
('ScanLM-32B-v4.0', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', '01.AI-32B', TRUE),
('Clinical-TII-v4.5', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'TII-13B', TRUE),
('Microsoft-TextAI-MoE-Sparse', 'Generación de Contenido', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Microsoft-MoE-Sparse', TRUE),
('Vision-Anthropic-v4.3', 'Visión y Multimodal', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Anthropic-8B', TRUE),
('TII-LexAI-70B', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'TII-70B', TRUE),
('RAGLM-14B-v1.5', 'Agentes y RAG', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Nexus-14B', TRUE),
('StatsLM-72B-v3.1', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'IBM-72B', TRUE),
('SyntaxLM-70B-v4.1', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Qwen-70B', TRUE),
('Google-TextAI-4x8B', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Google-4x8B', TRUE),
('CreativeLM-34B-v4.3', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'HuggingFace-34B', TRUE),
('TII-Chat-8x7B', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'TII-8x7B', TRUE),
('Stability-CalcAI-14B', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Stability-14B', TRUE),
('ProxDeep-Fin-14B-Instruct', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Cohere-14B', TRUE),
('ProxDeep-Copy-32B-Instruct', 'Generación de Contenido', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-32B', TRUE),
('TII-Scan-110B', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'TII-110B', TRUE),
('Nvidia-Analytics-34B', 'Análisis de Datos', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Nvidia-34B', TRUE),
('TII-Legal-32B', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-32B', TRUE),
('Mistral-Logic-MoE-Sparse', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Mistral-MoE-Sparse', TRUE),
('MoE-Nvidia-v2.2', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-13B', TRUE),
('ProxDeep-Pharma-34B-Instruct', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', '01.AI-34B', TRUE),
('Ledger-ProxDeep-v4.4', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'ProxDeep-7B', TRUE),
('MedLM-14B-v1.2', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'TII-14B', TRUE),
('ProxDeep-Copy-4x8B', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'ProxDeep-4x8B', TRUE),
('Clinical-DeepSeek-v4.3', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'DeepSeek-7B', TRUE),
('CareLM-34B-v1.4', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'ProxDeep-34B', TRUE),
('Qwen-EyeAI-4x8B', 'Visión y Multimodal', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Qwen-4x8B', TRUE),
('DeepSeek-SyntaxAI-4x8B', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'DeepSeek-4x8B', TRUE),
('Salesforce-ClinicalAI-110B', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Salesforce-110B', TRUE),
('Agent-Stability-v4.5', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Stability-72B', TRUE),
('Nexus-ScanAI-4x8B', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Nexus-4x8B', TRUE),
('Nvidia-LedgerAI-72B', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-72B', TRUE),
('Qwen-Ledger-8x7B', 'Finanzas y Auditoría', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Qwen-8x7B', TRUE),
('Nexus-CalcAI-70B', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nexus-70B', TRUE),
('Salesforce-ClinicalAI-4x8B', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Salesforce-4x8B', TRUE),
('JusticeLM-MoE-Sparse-v3.3', 'Legal y Cumplimiento', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Mistral-MoE-Sparse', TRUE),
('CareLM-7B-v1.2', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', '01.AI-7B', TRUE),
('Mistral-MoE-70B', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Mistral-70B', TRUE),
('IBM-ImageAI-110B', 'Visión y Multimodal', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'IBM-110B', TRUE),
('ProxDeep-Instruct-72B-Instruct', 'Agentes y RAG', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Mistral-72B', TRUE),
('Qwen-WriterAI-70B', 'Generación de Contenido', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Qwen-70B', TRUE),
('EleutherAI-HealthAI-32B', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'EleutherAI-32B', TRUE),
('Care-Microsoft-v4.4', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Microsoft-MoE-Sparse', TRUE),
('Meta-Clinical-14B', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Meta-14B', TRUE),
('SyntaxLM-32B-v4.0', 'Código y Desarrollo', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Google-32B', TRUE),
('ProxDeep-CodeLlama-32B-Instruct', 'Código y Desarrollo', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'DeepSeek-32B', TRUE),
('Compliance-Anthropic-v2.4', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Anthropic-8B', TRUE),
('WriterLM-8B-v3.1', 'Generación de Contenido', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Mistral-8B', TRUE),
('ProxDeep-Market-32B-Instruct', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Anthropic-32B', TRUE),
('ProxDeep-Scan-110B-Instruct', 'Visión y Multimodal', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'ProxDeep-110B', TRUE),
('RAGLM-7B-v3.2', 'Agentes y RAG', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Qwen-7B', TRUE),
('Meta-Syntax-MoE-Sparse', 'Código y Desarrollo', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Meta-MoE-Sparse', TRUE),
('ProxDeep-Econ-4x8B-Instruct', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'ProxDeep-4x8B', TRUE),
('Cohere-Health-13B', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Cohere-13B', TRUE),
('IBM-DoctorAI-110B', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'IBM-110B', TRUE),
('Pharma-HuggingFace-v2.2', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-4x8B', TRUE),
('Upstage-Engine-14B', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Upstage-14B', TRUE),
('Google-MathAI-7B', 'Análisis de Datos', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Google-7B', TRUE),
('DeepSeek-ContractAI-34B', 'Legal y Cumplimiento', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'DeepSeek-34B', TRUE),
('MedLM-72B-v4.1', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Salesforce-72B', TRUE),
('Salesforce-MoEAI-32B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Salesforce-32B', TRUE),
('CoderLM-110B-v3.3', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Anthropic-110B', TRUE),
('TII-Image-8B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'TII-8B', TRUE),
('Econ-Cohere-v4.3', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Cohere-14B', TRUE),
('ProxDeep-CodeLlamaAI-14B', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'ProxDeep-14B', TRUE),
('ProxDeep-Reasoning-8x7B-Instruct', 'Agentes y RAG', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Meta-8x7B', TRUE),
('ProxDeep-Health-MoE-Sparse-Instruct', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Meta-MoE-Sparse', TRUE),
('Mistral-Care-14B', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Mistral-14B', TRUE),
('MathLM-4x8B-v1.5', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', '01.AI-4x8B', TRUE),
('ProxDeep-Dev-8x7B-Instruct', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Mistral-8x7B', TRUE),
('Build-EleutherAI-v3.5', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'EleutherAI-34B', TRUE),
('ProxDeep-Justice-MoE-Sparse-Instruct', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'HuggingFace-MoE-Sparse', TRUE),
('Google-Dev-14B', 'Código y Desarrollo', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Google-14B', TRUE),
('Meta-Math-13B', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Meta-13B', TRUE),
('Ledger-DeepSeek-v1.1', 'Finanzas y Auditoría', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'DeepSeek-4x8B', TRUE),
('Stability-Content-MoE-Sparse', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-MoE-Sparse', TRUE),
('Audit-01.AI-v4.3', 'Finanzas y Auditoría', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', '01.AI-110B', TRUE),
('ProxDeep-MultiAI-4x8B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'ProxDeep-4x8B', TRUE),
('Health-Nexus-v2.5', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Nexus-8x7B', TRUE),
('ProxDeep-Trade-32B-Instruct', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'EleutherAI-32B', TRUE),
('Cohere-Eye-110B', 'Visión y Multimodal', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Cohere-110B', TRUE),
('DataLM-34B-v2.2', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Salesforce-34B', TRUE),
('Microsoft-Instruct-70B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Microsoft-70B', TRUE),
('Microsoft-Reasoning-70B', 'Agentes y RAG', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Microsoft-70B', TRUE),
('Meta-Quant-4x8B', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Meta-4x8B', TRUE),
('Anthropic-FinAI-70B', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Anthropic-70B', TRUE),
('Cohere-ProgrammerAI-14B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Cohere-14B', TRUE),
('ProxDeep-Math-32B-Instruct', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Google-32B', TRUE),
('Nvidia-MoEAI-4x8B', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-4x8B', TRUE),
('LegalLM-8x7B-v1.1', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Google-8x7B', TRUE),
('Stability-DevAI-8B', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Stability-8B', TRUE),
('Engine-Anthropic-v4.0', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Anthropic-70B', TRUE),
('HealthLM-MoE-Sparse-v3.4', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', '01.AI-MoE-Sparse', TRUE),
('Math-Salesforce-v3.1', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Salesforce-14B', TRUE),
('ProxDeep-Orchestrator-8B-Instruct', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-8B', TRUE),
('ProxDeep-Bio-8B-Instruct', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Google-8B', TRUE),
('ProxDeep-MoE-8x7B-Instruct', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Nexus-8x7B', TRUE),
('DoctorLM-13B-v3.2', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Qwen-13B', TRUE),
('RAGLM-13B-v4.1', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-13B', TRUE),
('CoderLM-8x7B-v1.5', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Nexus-8x7B', TRUE),
('Meta-HealthAI-70B', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Meta-70B', TRUE),
('Upstage-Instruct-13B', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Upstage-13B', TRUE),
('Nexus-CareAI-13B', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Nexus-13B', TRUE),
('ProxDeep-Syntax-13B-Instruct', 'Código y Desarrollo', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Mistral-13B', TRUE),
('Upstage-MarketAI-8x7B', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Upstage-8x7B', TRUE),
('TII-Justice-32B', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'TII-32B', TRUE),
('HuggingFace-DoctorAI-70B', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'HuggingFace-70B', TRUE),
('DevLM-13B-v1.0', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'TII-13B', TRUE),
('ClinicalLM-8x7B-v3.0', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Nvidia-8x7B', TRUE),
('Google-Writer-14B', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Google-14B', TRUE),
('ProxDeep-Draft-MoE-Sparse-Instruct', 'Generación de Contenido', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Meta-MoE-Sparse', TRUE),
('Bio-Salesforce-v1.4', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Salesforce-13B', TRUE),
('EleutherAI-Build-34B', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'EleutherAI-34B', TRUE),
('ProxDeep-Lex-110B-Instruct', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'DeepSeek-110B', TRUE),
('Draft-Nexus-v1.1', 'Generación de Contenido', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Nexus-72B', TRUE),
('Pharma-DeepSeek-v4.5', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'DeepSeek-14B', TRUE),
('Meta-EngineAI-34B', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Meta-34B', TRUE),
('Mistral-Data-7B', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Mistral-7B', TRUE),
('Nvidia-StatsAI-4x8B', 'Análisis de Datos', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Nvidia-4x8B', TRUE),
('ChatLM-110B-v2.4', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'TII-110B', TRUE),
('RAG-Google-v3.0', 'Agentes y RAG', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Google-70B', TRUE),
('TII-Contract-8x7B', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'TII-8x7B', TRUE),
('Qwen-VisionAI-34B', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Qwen-34B', TRUE),
('Qwen-TextAI-7B', 'Generación de Contenido', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Qwen-7B', TRUE),
('Google-FinAI-MoE-Sparse', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Google-MoE-Sparse', TRUE),
('Bio-IBM-v2.2', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'IBM-70B', TRUE),
('01.AI-Calc-70B', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', '01.AI-70B', TRUE),
('IBM-EyeAI-4x8B', 'Visión y Multimodal', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'IBM-4x8B', TRUE),
('Stability-ContractAI-8B', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Stability-8B', TRUE),
('Stability-Dev-110B', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Stability-110B', TRUE),
('ClinicalLM-14B-v1.2', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'ProxDeep-14B', TRUE),
('Health-ProxDeep-v4.4', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'ProxDeep-13B', TRUE),
('DeepSeek-PharmaAI-72B', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'DeepSeek-72B', TRUE),
('ProxDeep-Calc-110B-Instruct', 'Análisis de Datos', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Cohere-110B', TRUE),
('ProxDeep-Logic-13B-Instruct', 'Código y Desarrollo', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'HuggingFace-13B', TRUE),
('DoctorLM-8B-v1.0', 'Salud y BioMedicina', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Meta-8B', TRUE),
('EleutherAI-CoderAI-MoE-Sparse', 'Código y Desarrollo', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'EleutherAI-MoE-Sparse', TRUE),
('HuggingFace-WriterAI-8x7B', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'HuggingFace-8x7B', TRUE),
('HuggingFace-Quant-34B', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'HuggingFace-34B', TRUE),
('Meta-Audit-MoE-Sparse', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Meta-MoE-Sparse', TRUE),
('RAGLM-32B-v1.5', 'Agentes y RAG', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Upstage-32B', TRUE),
('IBM-Dev-14B', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'IBM-14B', TRUE),
('Nvidia-CoderAI-14B', 'Código y Desarrollo', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Nvidia-14B', TRUE),
('HealthLM-14B-v4.2', 'Salud y BioMedicina', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'ProxDeep-14B', TRUE),
('Anthropic-Programmer-32B', 'Código y Desarrollo', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Anthropic-32B', TRUE),
('Stability-Agent-7B', 'Agentes y RAG', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-7B', TRUE),
('Google-Med-13B', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Google-13B', TRUE),
('Health-EleutherAI-v1.0', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'EleutherAI-32B', TRUE),
('Calc-01.AI-v3.5', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', '01.AI-13B', TRUE),
('Nexus-Writer-13B', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nexus-13B', TRUE),
('Upstage-LexAI-70B', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Upstage-70B', TRUE),
('Pharma-HuggingFace-v4.3', 'Salud y BioMedicina', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-8B', TRUE),
('Multi-Microsoft-v4.0', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Microsoft-MoE-Sparse', TRUE),
('IBM-HealthAI-MoE-Sparse', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'IBM-MoE-Sparse', TRUE),
('CopyLM-32B-v3.2', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Google-32B', TRUE),
('EleutherAI-Analytics-13B', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'EleutherAI-13B', TRUE),
('Fin-Nexus-v1.1', 'Finanzas y Auditoría', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Nexus-8B', TRUE),
('Meta-ComplianceAI-72B', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Meta-72B', TRUE),
('CalcLM-110B-v4.0', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-110B', TRUE),
('Mistral-Agent-8x7B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Mistral-8x7B', TRUE),
('Meta-CalcAI-72B', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Meta-72B', TRUE),
('ProxDeep-Creative-70B-Instruct', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'DeepSeek-70B', TRUE),
('Mistral-DataAI-110B', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Mistral-110B', TRUE),
('Data-DeepSeek-v4.0', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'DeepSeek-7B', TRUE),
('Anthropic-ContractAI-70B', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Anthropic-70B', TRUE),
('ProxDeep-RAG-8B-Instruct', 'Agentes y RAG', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', '01.AI-8B', TRUE),
('ProxDeep-Doctor-7B-Instruct', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'TII-7B', TRUE),
('LegalLM-8B-v3.2', 'Legal y Cumplimiento', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Microsoft-8B', TRUE),
('BuildLM-72B-v2.5', 'Código y Desarrollo', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'Stability-72B', TRUE),
('JusticeLM-14B-v2.5', 'Legal y Cumplimiento', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'ProxDeep-14B', TRUE),
('ProxDeep-Data-34B-Instruct', 'Análisis de Datos', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Google-34B', TRUE),
('ProxDeep-Quant-13B-Instruct', 'Finanzas y Auditoría', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', '01.AI-13B', TRUE),
('Contract-Upstage-v4.2', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Upstage-4x8B', TRUE),
('Upstage-Creative-34B', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Upstage-34B', TRUE),
('Stability-BuildAI-72B', 'Código y Desarrollo', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Stability-72B', TRUE),
('ProxDeep-Health-4x8B-Instruct', 'Salud y BioMedicina', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Mistral-4x8B', TRUE),
('IBM-ReasoningAI-110B', 'Agentes y RAG', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'IBM-110B', TRUE),
('ProxDeep-Lex-MoE-Sparse-Instruct', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'EleutherAI-MoE-Sparse', TRUE),
('Anthropic-Analytics-13B', 'Análisis de Datos', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Anthropic-13B', TRUE),
('Anthropic-StatsAI-72B', 'Análisis de Datos', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'Anthropic-72B', TRUE),
('CodeLlamaLM-34B-v1.1', 'Código y Desarrollo', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nvidia-34B', TRUE),
('Microsoft-Math-MoE-Sparse', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Microsoft-MoE-Sparse', TRUE),
('Contract-Upstage-v3.1', 'Legal y Cumplimiento', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Upstage-13B', TRUE),
('Nexus-InstructAI-14B', 'Agentes y RAG', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Nexus-14B', TRUE),
('Stability-MarketAI-MoE-Sparse', 'Finanzas y Auditoría', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Stability-MoE-Sparse', TRUE),
('BioLM-72B-v2.5', 'Salud y BioMedicina', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'TII-72B', TRUE),
('Stability-Content-70B', 'Generación de Contenido', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Stability-70B', TRUE),
('CodeLlamaLM-7B-v3.3', 'Código y Desarrollo', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'TII-7B', TRUE),
('ProxDeep-Bio-7B-Instruct', 'Salud y BioMedicina', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Google-7B', TRUE),
('ProxDeep-Legal-7B-Instruct', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Qwen-7B', TRUE),
('HuggingFace-LegalAI-13B', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'HuggingFace-13B', TRUE),
('Scan-HuggingFace-v2.1', 'Visión y Multimodal', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'HuggingFace-110B', TRUE),
('Salesforce-ScanAI-32B', 'Visión y Multimodal', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Salesforce-32B', TRUE),
('ProxDeep-Multi-7B-Instruct', 'Visión y Multimodal', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'Nexus-7B', TRUE),
('Bio-Microsoft-v4.0', 'Salud y BioMedicina', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Microsoft-34B', TRUE),
('EleutherAI-TextAI-MoE-Sparse', 'Generación de Contenido', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'EleutherAI-MoE-Sparse', TRUE),
('ContentLM-32B-v1.3', 'Generación de Contenido', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'EleutherAI-32B', TRUE),
('EleutherAI-Justice-8B', 'Legal y Cumplimiento', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'EleutherAI-8B', TRUE),
('Nvidia-Justice-72B', 'Legal y Cumplimiento', 'Destaca en razonamiento lógico y tareas matemáticas complejas para análisis corporativo.', 'Nvidia-72B', TRUE),
('Stability-DataAI-110B', 'Análisis de Datos', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'Stability-110B', TRUE),
('IBM-Fin-72B', 'Finanzas y Auditoría', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'IBM-72B', TRUE),
('HuggingFace-DoctorAI-110B', 'Salud y BioMedicina', 'Versión cuantizada a 4-bits que permite correr en hardware modesto sin perder precisión técnica.', 'HuggingFace-110B', TRUE),
('ProxDeep-Trade-4x8B-Instruct', 'Finanzas y Auditoría', 'Ideal para despliegues On-Premise. Cumple con normativas ISO y SOC2 en tratamiento de información.', 'EleutherAI-4x8B', TRUE),
('TextLM-14B-v1.2', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Stability-14B', TRUE),
('MedLM-13B-v2.2', 'Salud y BioMedicina', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'TII-13B', TRUE),
('Syntax-DeepSeek-v1.5', 'Código y Desarrollo', 'Modelo especializado con un corpus corporativo masivo para garantizar respuestas libres de alucinaciones.', 'DeepSeek-32B', TRUE),
('ProxDeep-Law-34B-Instruct', 'Legal y Cumplimiento', 'SML ajustado para alta eficiencia y latencia mínima en entornos de producción restrictivos.', 'Microsoft-34B', TRUE),
('LedgerLM-MoE-Sparse-v4.1', 'Finanzas y Auditoría', 'Integración perfecta con sistemas RAG (Retrieval-Augmented Generation) para búsqueda en bases documentales.', 'HuggingFace-MoE-Sparse', TRUE),
('Reasoning-Google-v4.0', 'Agentes y RAG', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Google-72B', TRUE),
('ProxDeep-Analytics-14B-Instruct', 'Análisis de Datos', 'Arquitectura Mixture of Experts optimizada para inferencia en servidores de bajo costo.', 'Stability-14B', TRUE),
('ProxDeep-Writer-8x7B-Instruct', 'Generación de Contenido', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'Microsoft-8x7B', TRUE),
('Trade-IBM-v4.3', 'Finanzas y Auditoría', 'Modelo ligero que supera a GPT-3.5 en benchmarks específicos de la industria.', 'IBM-13B', TRUE);
